Models/Discussion.cs
using ShinyRockForum.Data;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShinyRockForum.Models
{
    public class Discussion
    {
        //Discussion Id
        public int DiscussionId { get; set; }

        //Title
        [Required(ErrorMessage = "A description is required.")]
        public string Title { get; set; } = string.Empty;
        //Content
        [Required(ErrorMessage = "A description is required.")]
        public string Content { get; set; } = string.Empty;

        //ImageFilename
        public string? ImageFilename { get; set; } //Nullable

        //File storage
        [NotMapped]
        [Display(Name = "Photograph")]
        public IFormFile? ImageFile { get; set; }

        //CreateDate
        public DateTime CreateDate { get; set; } = DateTime.Now;
        
        //navigation property
        public ICollection<Comment>? Comments { get; set; } //Nullable

        // Foreign key for creator
        public string ApplicationUserId { get; set; } = string.Empty;

        // Navigation property
        public ApplicationUser? ApplicationUser { get; set; } // nullable!!!


    }
}

Controllers/DiscussionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShinyRockForum.Data;
using ShinyRockForum.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authentication.Cookies;

//NEW FILE WHY ITS WORKING BUT NOT....I DONT KNOW

namespace ShinyRockForum.Controllers
{
    [Authorize]
    public class DiscussionController : Controller
    {
        private readonly ShinyRockForumContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DiscussionController(ShinyRockForumContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        //Removed discussions/details method

        // GET: Discussions/Index
        [Route("Discussions/Index")]
        public async Task<IActionResult> Index()
        {
            string userID = _userManager.GetUserId(User);

            Console.WriteLine("FETCHING ITEMS");

            var discussions = await _context.Discussion
                .Where(m => m.ApplicationUserId == userID)
                .Include(d => d.Comments)
                .OrderByDescending(d => d.CreateDate)
                .ToListAsync();



            Console.WriteLine("THERE ARE THESE MANY ITEMS" + discussions.Count);

            return View(discussions);
        }

        // GET: Discussions/Edit
        public async Task<IActionResult> Edit(int? id)
        {

            Console.WriteLine("IN EDIT GET");



            if (id == null)
            {
                return NotFound();
            }

            var userID = _userManager.GetUserId(User);
            var discussion = await _context.Discussion
                .Include(d => d.Comments)
                .Where(m => m.ApplicationUserId == userID)
                .FirstOrDefaultAsync(m => m.DiscussionId == id);

            if (discussion == null)
            {
                return NotFound();
            }

            return View(discussion);
        }

        // POST: Discussions/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DiscussionId,Title,Content,ImageFile")] Discussion discussion)
        {

            discussion.ApplicationUserId = _userManager.GetUserId(User);

            if (id != discussion.DiscussionId)
            {
                return NotFound();
            }

            if (discussion.ImageFile != null)
            {
                //set the image filename to a guid
                discussion.ImageFilename = Guid.NewGuid().ToString() + Path.GetExtension(discussion.ImageFile?.FileName);
            }

            if (ModelState.IsValid)
            {

                _context.Update(discussion);
                await _context.SaveChangesAsync();

                if (discussion.ImageFile != null)
                {
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "photos", discussion.ImageFilename);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await discussion.ImageFile.CopyToAsync(fileStream);
                    }
                }

                return RedirectToAction("Index", "Home");
            }
            return View(discussion);
        }

        // GET: Discussions/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userID = _userManager.GetUserId(User);

            var discussion = await _context.Discussion
                .Include(d => d.Comments)
                .Where(m => m.ApplicationUserId == userID)
                .FirstOrDefaultAsync(m => m.DiscussionId == id);

            if (discussion == null)
            {
                return NotFound();
            }

            return View(discussion);
        }

        // POST: Discussions/Delete

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userID = _userManager.GetUserId(User);

            var discussion = await _context.Discussion
                .Where(m => m.ApplicationUserId == userID)
                .FirstOrDefaultAsync(m => m.DiscussionId == id);

            if (discussion == null)
            {
                return NotFound();
            }
            else
            {
                _context.Discussion.Remove(discussion);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }




        // GET: Discussions/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Discussions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DiscussionId,Title,Content,ImageFile")] Discussion discussion)
        {
            //set the create date to now
            discussion.CreateDate = DateTime.Now;

            discussion.ApplicationUserId = _userManager.GetUserId(User);
            Console.WriteLine(discussion.ApplicationUserId);

            if (discussion.ImageFile != null)
            {
                //set the image filename to a guid
                discussion.ImageFilename = Guid.NewGuid().ToString() + Path.GetExtension(discussion.ImageFile?.FileName);
            }

            if (ModelState.IsValid)
            {
                _context.Add(discussion);
                await _context.SaveChangesAsync();

                if (discussion.ImageFile != null)
                {
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "photos", discussion.ImageFilename);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await discussion.ImageFile.CopyToAsync(fileStream);
                    }

                }

                return RedirectToAction("Index", "Home");
            }
            

            return View(discussion);
        }


    }
}

Controllers/DiscussionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShinyRockForum.Data;
using ShinyRockForum.Models;


namespace ShinyRockForum.Controllers
{
    [Authorize]
    public class DiscussionsController : Controller
    {
        private readonly ShinyRockForumContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DiscussionsController(ShinyRockForumContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        //Removed discussions/details method


        // GET: Discussions/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userID = _userManager.GetUserId(User);
            var discussion = await _context.Discussion
                .Where(m => m.ApplicationUserId == userID)
                .FirstOrDefaultAsync(m => m.DiscussionId == id);

            if (discussion == null)
            {
                return NotFound();
            }

            return View(discussion);
        }

        // POST: Discussions/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DiscussionId,Title,Content,ImageFile")] Discussion discussion)
        {

            discussion.ApplicationUserId = _userManager.GetUserId(User);

            if (id != discussion.DiscussionId)
            {
                return NotFound();
            }

            if (discussion.ImageFile != null)
            {
                //set the image filename to a guid
                discussion.ImageFilename = Guid.NewGuid().ToString() + Path.GetExtension(discussion.ImageFile?.FileName);
            }

            if (ModelState.IsValid)
            {
                
                _context.Update(discussion);
                await _context.SaveChangesAsync();

                if (discussion.ImageFile != null)
                {
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "photos", discussion.ImageFilename);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await discussion.ImageFile.CopyToAsync(fileStream);
                    }
                }
                               
                return RedirectToAction("Index", "Home");
            }
            return View(discussion);
        }

        // GET: Discussions/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userID = _userManager.GetUserId(User);

            var discussion = await _context.Discussion
                .Where(m => m.ApplicationUserId == userID)
                .FirstOrDefaultAsync(m => m.DiscussionId == id);

            if (discussion == null)
            {
                return NotFound();
            }

            return View(discussion);
        }

        // POST: Discussions/Delete

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userID = _userManager.GetUserId(User);

            var discussion = await _context.Discussion
                .Where(m => m.ApplicationUserId == userID)
                .FirstOrDefaultAsync(m => m.DiscussionId == id);

            if (discussion == null)
            {
                return NotFound();
            }
            else
            {
                _context.Discussion.Remove(discussion);
            }

            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index", "Home");
        }



        // GET: Discussions/Index
        public IActionResult Index()
        {
            string userID = _userManager.GetUserId(User);
            var discussions = _context.Discussion
                .Where(m => m.ApplicationUserId == userID)
                .OrderByDescending(m => m.CreateDate)
                .ToList();

            return View(discussions);
        }

        // GET: Discussions/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Discussions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DiscussionId,Title,Content,ImageFile")] Discussion discussion)
        {
            //set the create date to now
            discussion.CreateDate = DateTime.Now;
            discussion.ApplicationUserId = _userManager.GetUserId(User);

            if (discussion.ImageFile != null)
            {
                //set the image filename to a guid
                discussion.ImageFilename = Guid.NewGuid().ToString() + Path.GetExtension(discussion.ImageFile?.FileName);
            }

            if (ModelState.IsValid)
            {
                _context.Add(discussion);
                await _context.SaveChangesAsync();

                if (discussion.ImageFile != null)
                {
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "photos", discussion.ImageFilename);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await discussion.ImageFile.CopyToAsync(fileStream);
                    }

                }

                return RedirectToAction("Index", "Home");
            }
            else { Console.WriteLine("BANANA"); }

            return View(discussion);
        }

        
    }
}

Views/Discussion/Create.cshtml
@model ShinyRockForum.Models.Discussion

@{
    ViewData["Title"] = "Create";
}

<h1>Post something cool!</h1>

<h4>What would you like to talk about?</h4>
<hr />

<div>
    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group col-md-4">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <textarea asp-for="Content" class="form-control" rows="4"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="ImageFile" class="form-label"></label>
            <input type="file" asp-for="ImageFile" class="form-control" />
            <span asp-validation-for="ImageFile" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary m-2" />
        </div>
    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Discussion/Delete.cshtml
@model ShinyRockForum.Models.Discussion
@using Microsoft.AspNetCore.Identity
@using ShinyRockForum.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Delete";
    string imageUrl = Url.Content("/photos/" + @Model.ImageFilename);
    string userName = UserManager.FindByIdAsync(Model.ApplicationUserId).Result.UserName;


}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<hr />
<div class="card border-secondary mb-1 rounded-0">
    <input type="hidden" asp-for="DiscussionId" />
    <div class="card-header fw-bold">
        <a>@Model.Title</a>
    </div>
    <div class="card-body text-secondary">
        <p class="card-text">@userName : @Model.CreateDate.ToString("MMM dd yyyy")</p>

        <div class="mb-2">
            <p class="card-text">@Model.Content</p>
        </div>
        @if (!string.IsNullOrEmpty(Model.ImageFilename))
        {
            <div>
                <img src="@imageUrl" class="img-fluid " alt="Image" />
            </div>
        }

        <p class="card-text">Comments: @Model.Comments.Count</p>

    </div>
    <div class="justify-content-end d-flex gap-2 mb-2 mx-2">
    <form asp-action="Delete">
        <input type="hidden" asp-for="DiscussionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-primary" asp-action="Index">Back</a>
    </form>
    </div>
</div>

Views/Discussion/Edit.cshtml
@model ShinyRockForum.Models.Discussion

@{
    ViewData["Title"] = "Edit";
}


<h4>Edit discussion</h4>
<hr />

<div>
    <form asp-action="Edit" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="DiscussionId" />
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <textarea asp-for="Content" class="form-control" rows="4"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <p>Change image:</p>
        <div class="form-group mb-3">
            <label asp-for="ImageFile" class="form-label"></label>
            <input type="file" asp-for="ImageFile" class="form-control" />
            <span asp-validation-for="ImageFile" class="text-danger"></span>
        </div>
        <div class="form-group justify-content-end d-flex gap-2 mb-2 mx-2">
            <input type="submit" value="Save" class="btn btn-primary"/> |
            <a class="btn btn-primary" asp-controller="Home" asp-action="GetDiscussion" asp-route-id="@Model.DiscussionId">Back</a>
        </div>
    </form>
</div>


<div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Discussion/Index.cshtml
@model List<ShinyRockForum.Models.Discussion>
@using Microsoft.AspNetCore.Identity
@using ShinyRockForum.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "";
}

<h4>Your posts:</h4>
<hr />

@* @{ *@
@*     if (Model == null) *@
@*     { *@
@*         <h1>Model Is Null</h1> *@
@*     } *@

@*     else if (Model.Count == 0) *@
@*     { *@
@*         <h1>No Posts Found</h1> *@
@*     } *@
@*     else *@
@*     { *@
@*         foreach (var discussion in Model) *@
@*         { *@
@*             <h1>@discussion.Title</h1> *@
@*         } *@
@*     } *@
@* } *@
@{

    if (Model == null)
    {
        <h1>Something's gone wrong. Model Is Null</h1>
    }
    else if (Model.Count == 0)
    {
        <p>You have not posted anything yet. Why not <a asp-area="" asp-controller="Discussion" asp-action="Create">post something</a>?</p>
    }
    else
    {
        foreach (var discussion in Model)
        {

            string userName = UserManager.FindByIdAsync(discussion.ApplicationUserId).Result.UserName;
            string imageUrl = Url.Content($"/photos/{discussion.ImageFilename}");

            <div class="card border-secondary mb-3 rounded-0" style="m">
                <div class="card-header">
                    <a class="nav-link text-dark fw-semibold" asp-area="" asp-controller="Home" asp-action="GetDiscussion" asp-route-id="@discussion.DiscussionId">@discussion.Title</a>
                </div>
                <div class="card-body text-secondary row g-0">

                    <p class="card-text">@userName : @discussion.CreateDate.ToString("MMM dd yyyy")</p>

                     @if (!string.IsNullOrEmpty(discussion.ImageFilename))
                        {
                            <div class="col-md-3 p-2">
                                <img src="@imageUrl" class="img-fluid " alt="Image" />
                            </div>
                        }

                    <div class="col-md-9 mb-2">
                        <p class="card-text">@discussion.Content</p>
                    </div>

                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="GetDiscussion" asp-route-id="@discussion.DiscussionId">Comments: @discussion.Comments.Count</a>
                </div>
            </div>
        }
    }
}